spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      username: micro 
      password: micro
      
ribbon:
  eureka:
    enabled: true
    
test:
  accounts:
    - id: 1
      number: 0654321789
      balance: 2500
      customerId: 1
    - id: 2
      number: 0654321780
      balance: 0
      customerId: 1
    - id: 3
      number: 0650981789
      balance: 12000
      customerId: 2